# Generated by Django 4.1.7 on 2023-03-19 11:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo', '0002_comments_image_task_executors_delete_assignment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comments',
            name='photos',
        ),
        migrations.AddField(
            model_name='comments',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='comment_images', to='todo.image'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_comments', to='todo.task'),
        ),
        migrations.AlterField(
            model_name='task',
            name='executors',
            field=models.ManyToManyField(blank=True, related_name='task_executors', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='task_images', to='todo.image'),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='status', to='todo.taskstatus'),
        ),
    ]
