# Generated by Django 4.1.7 on 2023-03-19 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_comments_comments'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='comments',
            new_name='comment',
        ),
    ]
