# Generated by Django 4.1.7 on 2023-03-19 13:45
from django.db import migrations


def add_default_statuses(apps, schema_editor):
    task_status = apps.get_model('todo', 'TaskStatus')
    task_status.objects.create(
        name='Нова'
    )
    task_status.objects.create(
        name='В роботі'
    )
    task_status.objects.create(
        name='Завершено'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0005_rename_comments_comments_comment'),
    ]

    operations = [
        migrations.RunPython(add_default_statuses),
    ]
